### ISSUE TITLE
add -silent 

### ISSUE THREAD

**Issue by tahasamar** [hakluke/hakip2host#2]
hi 
please add a -silent flag so we can chain the results to another tool

**Comment by hakluke** [comment]
If you just want the hostnames you can just use cut:

<img width="442" alt="image" src="https://github.com/hakluke/hakip2host/assets/13975395/c6e82291-7521-4f0c-bc1d-90a7e37e62ff">

**Comment by hakluke** [comment]
I don't want to add any additional code to hakip2host for this functionality
